-- M12.2 Core Domain & Persistence foundation.
-- UUIDv7 values are generated by the application; the database does not invent aggregate identifiers.

CREATE TYPE learning_version_status AS ENUM ('DRAFT', 'PUBLISHED');
CREATE TYPE verification_attempt_status AS ENUM ('PENDING', 'RUNNING', 'COMPLETED');
CREATE TYPE verification_outcome AS ENUM ('PASSED', 'FAILED', 'ERROR');
CREATE TYPE competency_projection_status AS ENUM ('NOT_YET_EVIDENCED', 'EVIDENCED');
CREATE TYPE cohort_status AS ENUM ('DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED');
CREATE TYPE membership_status AS ENUM ('ENROLLED', 'REMOVED');

CREATE TABLE tenants (
  id uuid PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE members (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  auth_user_id text NOT NULL,
  display_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, auth_user_id)
);
CREATE TABLE courses (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key)
);
CREATE TABLE course_versions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  course_id uuid NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
  version integer NOT NULL CHECK (version > 0),
  status learning_version_status NOT NULL DEFAULT 'DRAFT',
  title text NOT NULL,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, course_id, version),
  CHECK ((status = 'DRAFT' AND published_at IS NULL) OR (status = 'PUBLISHED' AND published_at IS NOT NULL))
);
CREATE INDEX course_versions_tenant_status_idx ON course_versions (tenant_id, status);
CREATE TABLE chapter_versions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  course_version_id uuid NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT,
  position integer NOT NULL CHECK (position >= 0),
  title text NOT NULL,
  UNIQUE (tenant_id, id),
  UNIQUE (course_version_id, position)
);
CREATE TABLE lesson_versions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  chapter_version_id uuid NOT NULL REFERENCES chapter_versions(id) ON DELETE RESTRICT,
  position integer NOT NULL CHECK (position >= 0),
  title text NOT NULL,
  content jsonb NOT NULL,
  UNIQUE (tenant_id, id),
  UNIQUE (chapter_version_id, position)
);
CREATE TABLE skills (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  key text NOT NULL,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key)
);
CREATE TABLE enrollments (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  course_version_id uuid NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, learner_id, course_version_id)
);
CREATE TABLE lesson_progress (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  lesson_version_id uuid NOT NULL REFERENCES lesson_versions(id) ON DELETE RESTRICT,
  state text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, learner_id, lesson_version_id)
);
CREATE TABLE practice_definitions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  lesson_version_id uuid NOT NULL REFERENCES lesson_versions(id) ON DELETE RESTRICT,
  key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, lesson_version_id, key)
);
CREATE TABLE practice_revisions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  practice_id uuid NOT NULL REFERENCES practice_definitions(id) ON DELETE RESTRICT,
  skill_id uuid NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
  revision_number integer NOT NULL CHECK (revision_number > 0),
  definition jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, practice_id, revision_number)
);
CREATE TABLE practice_submissions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  practice_revision_id uuid NOT NULL REFERENCES practice_revisions(id) ON DELETE RESTRICT,
  attempt_number integer NOT NULL CHECK (attempt_number > 0),
  request_id text NOT NULL,
  artifact jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, learner_id, practice_revision_id, attempt_number),
  UNIQUE (tenant_id, learner_id, practice_revision_id, request_id)
);
CREATE TABLE project_definitions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  key text NOT NULL,
  title text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key)
);
CREATE TABLE project_artifacts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  project_definition_id uuid NOT NULL REFERENCES project_definitions(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id)
);
CREATE TABLE artifact_revisions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  artifact_id uuid NOT NULL REFERENCES project_artifacts(id) ON DELETE RESTRICT,
  revision_number integer NOT NULL CHECK (revision_number > 0),
  object_key text NOT NULL,
  content_hash text NOT NULL,
  sealed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, artifact_id, revision_number),
  UNIQUE (tenant_id, object_key)
);
CREATE TABLE project_submissions (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  artifact_revision_id uuid NOT NULL REFERENCES artifact_revisions(id) ON DELETE RESTRICT,
  request_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, learner_id, artifact_revision_id, request_id)
);
CREATE TABLE verification_attempts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  practice_submission_id uuid REFERENCES practice_submissions(id) ON DELETE RESTRICT,
  project_submission_id uuid REFERENCES project_submissions(id) ON DELETE RESTRICT,
  status verification_attempt_status NOT NULL DEFAULT 'PENDING',
  verifier_key text NOT NULL,
  verifier_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz,
  completed_at timestamptz,
  UNIQUE (tenant_id, id),
  CHECK (((practice_submission_id IS NOT NULL)::integer + (project_submission_id IS NOT NULL)::integer) = 1)
);
CREATE INDEX verification_attempts_tenant_status_idx ON verification_attempts (tenant_id, status);
CREATE TABLE verification_results (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  verification_attempt_id uuid NOT NULL UNIQUE REFERENCES verification_attempts(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  outcome verification_outcome NOT NULL,
  diagnostic jsonb,
  completed_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id)
);
CREATE INDEX verification_results_tenant_learner_outcome_idx ON verification_results (tenant_id, learner_id, outcome);
CREATE TABLE skill_evidence (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  skill_id uuid NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
  verification_result_id uuid NOT NULL REFERENCES verification_results(id) ON DELETE RESTRICT,
  issued_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, verification_result_id, skill_id)
);
CREATE INDEX skill_evidence_tenant_learner_skill_idx ON skill_evidence (tenant_id, learner_id, skill_id);
CREATE TABLE competency_states (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  skill_id uuid NOT NULL REFERENCES skills(id) ON DELETE RESTRICT,
  status competency_projection_status NOT NULL DEFAULT 'NOT_YET_EVIDENCED',
  evidence_count integer NOT NULL DEFAULT 0 CHECK (evidence_count >= 0),
  projected_at timestamptz NOT NULL,
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, learner_id, skill_id)
);
CREATE TABLE cohorts (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  key text NOT NULL,
  name text NOT NULL,
  status cohort_status NOT NULL DEFAULT 'DRAFT',
  version integer NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, key)
);
CREATE TABLE cohort_memberships (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  cohort_id uuid NOT NULL REFERENCES cohorts(id) ON DELETE RESTRICT,
  learner_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  status membership_status NOT NULL DEFAULT 'ENROLLED',
  enrolled_at timestamptz NOT NULL,
  removed_at timestamptz,
  UNIQUE (tenant_id, id),
  CHECK ((status = 'ENROLLED' AND removed_at IS NULL) OR (status = 'REMOVED' AND removed_at IS NOT NULL))
);
CREATE UNIQUE INDEX cohort_memberships_one_active_idx ON cohort_memberships (tenant_id, cohort_id, learner_id) WHERE status = 'ENROLLED';
CREATE TABLE learning_assignments (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  cohort_id uuid NOT NULL REFERENCES cohorts(id) ON DELETE RESTRICT,
  course_version_id uuid NOT NULL REFERENCES course_versions(id) ON DELETE RESTRICT,
  is_primary boolean NOT NULL DEFAULT true,
  assigned_at timestamptz NOT NULL,
  UNIQUE (tenant_id, id)
);
CREATE UNIQUE INDEX learning_assignments_one_primary_idx ON learning_assignments (tenant_id, cohort_id) WHERE is_primary;
CREATE TABLE instructor_cohort_roles (
  id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  cohort_id uuid NOT NULL REFERENCES cohorts(id) ON DELETE RESTRICT,
  instructor_id uuid NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (tenant_id, id),
  UNIQUE (tenant_id, cohort_id, instructor_id)
);
CREATE TABLE outbox_events (
  id uuid PRIMARY KEY,
  tenant_id uuid REFERENCES tenants(id) ON DELETE RESTRICT,
  aggregate_type text NOT NULL,
  aggregate_id text NOT NULL,
  event_type text NOT NULL,
  payload jsonb NOT NULL,
  occurred_at timestamptz NOT NULL,
  published_at timestamptz,
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0)
);
CREATE INDEX outbox_events_unpublished_idx ON outbox_events (published_at, occurred_at);
CREATE TABLE audit_events (
  id uuid PRIMARY KEY,
  tenant_id uuid REFERENCES tenants(id) ON DELETE RESTRICT,
  actor_type text NOT NULL,
  actor_id text,
  action text NOT NULL,
  resource_type text NOT NULL,
  resource_id text,
  metadata jsonb,
  occurred_at timestamptz NOT NULL
);
CREATE INDEX audit_events_tenant_occurred_idx ON audit_events (tenant_id, occurred_at);

ALTER TABLE course_versions ADD CONSTRAINT course_versions_same_tenant_fk FOREIGN KEY (tenant_id, course_id) REFERENCES courses(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE enrollments ADD CONSTRAINT enrollments_member_same_tenant_fk FOREIGN KEY (tenant_id, learner_id) REFERENCES members(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE enrollments ADD CONSTRAINT enrollments_course_version_same_tenant_fk FOREIGN KEY (tenant_id, course_version_id) REFERENCES course_versions(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE practice_revisions ADD CONSTRAINT practice_revision_skill_same_tenant_fk FOREIGN KEY (tenant_id, skill_id) REFERENCES skills(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE practice_submissions ADD CONSTRAINT practice_submission_member_same_tenant_fk FOREIGN KEY (tenant_id, learner_id) REFERENCES members(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE practice_submissions ADD CONSTRAINT practice_submission_revision_same_tenant_fk FOREIGN KEY (tenant_id, practice_revision_id) REFERENCES practice_revisions(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE project_submissions ADD CONSTRAINT project_submission_member_same_tenant_fk FOREIGN KEY (tenant_id, learner_id) REFERENCES members(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE project_submissions ADD CONSTRAINT project_submission_revision_same_tenant_fk FOREIGN KEY (tenant_id, artifact_revision_id) REFERENCES artifact_revisions(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE skill_evidence ADD CONSTRAINT skill_evidence_member_same_tenant_fk FOREIGN KEY (tenant_id, learner_id) REFERENCES members(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE skill_evidence ADD CONSTRAINT skill_evidence_skill_same_tenant_fk FOREIGN KEY (tenant_id, skill_id) REFERENCES skills(tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE skill_evidence ADD CONSTRAINT skill_evidence_result_same_tenant_fk FOREIGN KEY (tenant_id, verification_result_id) REFERENCES verification_results(tenant_id, id) ON DELETE RESTRICT;

CREATE OR REPLACE FUNCTION reject_update_delete_when_published() RETURNS trigger AS $$
BEGIN
  IF OLD.status = 'PUBLISHED' THEN RAISE EXCEPTION 'published learning versions are immutable'; END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER course_versions_immutable_after_publish BEFORE UPDATE OR DELETE ON course_versions FOR EACH ROW EXECUTE FUNCTION reject_update_delete_when_published();

CREATE OR REPLACE FUNCTION reject_artifact_revision_mutation_when_sealed() RETURNS trigger AS $$
BEGIN
  IF OLD.sealed_at IS NOT NULL OR EXISTS (SELECT 1 FROM project_submissions s WHERE s.artifact_revision_id = OLD.id) THEN
    RAISE EXCEPTION 'submitted/sealed artifact revisions are immutable';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER artifact_revisions_immutable_after_seal BEFORE UPDATE OR DELETE ON artifact_revisions FOR EACH ROW EXECUTE FUNCTION reject_artifact_revision_mutation_when_sealed();

CREATE OR REPLACE FUNCTION reject_append_only_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION '% is append-only', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER practice_submissions_append_only BEFORE UPDATE OR DELETE ON practice_submissions FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER project_submissions_append_only BEFORE UPDATE OR DELETE ON project_submissions FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER verification_results_append_only BEFORE UPDATE OR DELETE ON verification_results FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();
CREATE TRIGGER skill_evidence_append_only BEFORE UPDATE OR DELETE ON skill_evidence FOR EACH ROW EXECUTE FUNCTION reject_append_only_mutation();

CREATE OR REPLACE FUNCTION enforce_evidence_from_passed_verification() RETURNS trigger AS $$
DECLARE result_outcome verification_outcome;
BEGIN
  SELECT outcome INTO result_outcome FROM verification_results WHERE id = NEW.verification_result_id;
  IF result_outcome IS DISTINCT FROM 'PASSED' THEN RAISE EXCEPTION 'skill evidence requires PASSED authoritative verification'; END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER skill_evidence_requires_pass BEFORE INSERT ON skill_evidence FOR EACH ROW EXECUTE FUNCTION enforce_evidence_from_passed_verification();

COMMENT ON TABLE competency_states IS 'Derived read model only. Never an independent competence authority.';
COMMENT ON TABLE skill_evidence IS 'Canonical evidence record. Insert requires PASSED verification result.';
COMMENT ON TABLE verification_results IS 'Immutable authoritative verification result; ERROR means system/infrastructure failure, not learner failure.';
